# Generated by Django 3.0.6 on 2020-05-18 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='地图名称')),
                ('menu', models.CharField(max_length=120, verbose_name='地图介绍')),
                ('cover', models.ImageField(default='none.png', upload_to='map/', verbose_name='地图封面')),
                ('boss1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boos1', to='monsters.Monster', verbose_name='1层大怪')),
                ('boss2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boos2', to='monsters.Monster', verbose_name='2层大怪')),
                ('boss3', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boos3', to='monsters.Monster', verbose_name='3层大怪')),
                ('boss4', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boos4', to='monsters.Monster', verbose_name='4层大怪')),
                ('boss5', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boos5', to='monsters.Monster', verbose_name='5层大怪')),
                ('floor1', models.ManyToManyField(related_name='floor1', to='monsters.Monster', verbose_name='1层怪物')),
                ('floor2', models.ManyToManyField(related_name='floor2', to='monsters.Monster', verbose_name='2层怪物')),
                ('floor3', models.ManyToManyField(related_name='floor3', to='monsters.Monster', verbose_name='3层怪物')),
                ('floor4', models.ManyToManyField(related_name='floor4', to='monsters.Monster', verbose_name='4层怪物')),
                ('floor5', models.ManyToManyField(related_name='floor5', to='monsters.Monster', verbose_name='5层怪物')),
            ],
        ),
    ]
