# Generated by Django 3.0.6 on 2020-05-18 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        ('heroes', '0001_initial'),
        ('consumables', '0001_initial'),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='昵称')),
                ('HP', models.IntegerField(verbose_name='基础生命值')),
                ('MP', models.IntegerField(verbose_name='基础法力值')),
                ('att', models.IntegerField(verbose_name='基础攻击力')),
                ('baoji', models.FloatField(verbose_name='基础暴击概率')),
                ('xiaoguo', models.FloatField(verbose_name='基础暴击效果')),
                ('shanghai', models.FloatField(verbose_name='基础技能伤害')),
                ('now_HP', models.IntegerField(default=0, verbose_name='当前生命值')),
                ('now_MP', models.IntegerField(default=0, verbose_name='当前法力值')),
                ('exp', models.IntegerField(default=0, verbose_name='经验值')),
                ('gold', models.IntegerField(default=100, verbose_name='金币')),
                ('lv', models.IntegerField(default=1, verbose_name='等级')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.Hero', verbose_name='英雄')),
                ('map', models.ManyToManyField(to='maps.Map', verbose_name='已通关地图')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('portrait', models.ImageField(default='none.jpg', upload_to='portrait/', verbose_name='头像')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lasted_log', models.DateTimeField(auto_now=True, verbose_name='上次登录')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm', models.ManyToManyField(related_name='re_arm', to='equipments.Equipment', verbose_name='臂部')),
                ('back', models.ManyToManyField(related_name='re_back', to='equipments.Equipment', verbose_name='背部')),
                ('body', models.ManyToManyField(related_name='re_body', to='equipments.Equipment', verbose_name='身体')),
                ('face', models.ManyToManyField(related_name='re_face', to='equipments.Equipment', verbose_name='面部')),
                ('feet', models.ManyToManyField(related_name='re_feet', to='equipments.Equipment', verbose_name='足具')),
                ('head', models.ManyToManyField(related_name='re_head', to='equipments.Equipment', verbose_name='头部')),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Player', verbose_name='购买者')),
                ('l_hand', models.ManyToManyField(related_name='re_l_hand', to='equipments.Equipment', verbose_name='左手')),
                ('leg', models.ManyToManyField(related_name='re_leg', to='equipments.Equipment', verbose_name='腿部')),
                ('r_hand', models.ManyToManyField(related_name='re_r_hand', to='equipments.Equipment', verbose_name='右手')),
                ('waist', models.ManyToManyField(related_name='re_waist', to='equipments.Equipment', verbose_name='腰部')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='玩家'),
        ),
        migrations.CreateModel(
            name='Equipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.IntegerField(null=True, verbose_name='头部')),
                ('face', models.IntegerField(null=True, verbose_name='面部')),
                ('body', models.IntegerField(null=True, verbose_name='身体')),
                ('back', models.IntegerField(null=True, verbose_name='背部')),
                ('waist', models.IntegerField(null=True, verbose_name='腰部')),
                ('arm', models.IntegerField(null=True, verbose_name='臂部')),
                ('leg', models.IntegerField(null=True, verbose_name='腿部')),
                ('l_hand', models.IntegerField(null=True, verbose_name='左手')),
                ('r_hand', models.IntegerField(null=True, verbose_name='右手')),
                ('feet', models.IntegerField(null=True, verbose_name='足具')),
                ('HP', models.IntegerField(default=0, verbose_name='装备生命值')),
                ('MP', models.IntegerField(default=0, verbose_name='装备法力值')),
                ('att', models.IntegerField(default=0, verbose_name='装备攻击力')),
                ('baoji', models.FloatField(default=0, verbose_name='装备暴击概率')),
                ('xiaoguo', models.FloatField(default=0, verbose_name='装备暴击效果')),
                ('shanghai', models.FloatField(default=0, verbose_name='装备技能伤害')),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Player', verbose_name='装备者')),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumables', models.ManyToManyField(to='consumables.Consumables', verbose_name='药品背包')),
                ('equipments', models.ManyToManyField(to='equipments.Equipment', verbose_name='装备背包')),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Player', verbose_name='装备者')),
            ],
        ),
    ]
