# Generated by Django 3.0.6 on 2020-05-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='物品名称')),
                ('cover', models.ImageField(default='none.png', upload_to='consumable/', verbose_name='物品图标')),
                ('menu', models.CharField(max_length=120, verbose_name='介绍')),
                ('gold', models.IntegerField(verbose_name='所需金币')),
                ('method', models.TextField(default='', verbose_name='调用方法')),
            ],
        ),
    ]
