# Generated by Django 3.0.6 on 2020-05-18 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=32, verbose_name='英雄职业')),
                ('sex', models.CharField(max_length=12, verbose_name='英雄性别')),
                ('menu', models.CharField(max_length=120, verbose_name='介绍')),
                ('cover', models.ImageField(default='none.png', upload_to='hero/img/', verbose_name='英雄图标')),
                ('action', models.ImageField(default='none.png', upload_to='hero/act_gif/', verbose_name='英雄动作')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_HP', models.IntegerField(verbose_name='最大基础生命值')),
                ('min_HP', models.IntegerField(verbose_name='最小基础生命值')),
                ('max_MP', models.IntegerField(verbose_name='最大基础法力值')),
                ('min_MP', models.IntegerField(verbose_name='最小基础法力值')),
                ('max_att', models.IntegerField(verbose_name='最大基础攻击力')),
                ('min_att', models.IntegerField(verbose_name='最小基础攻击力')),
                ('max_baoji', models.FloatField(verbose_name='最大基础暴击概率')),
                ('min_baoji', models.FloatField(verbose_name='最小基础暴击概率')),
                ('max_xiaoguo', models.FloatField(verbose_name='最大基础暴击效果')),
                ('min_xiaoguo', models.FloatField(verbose_name='最小基础暴击效果')),
                ('max_shanghai', models.FloatField(verbose_name='最大基础技能伤害')),
                ('min_shanghai', models.FloatField(verbose_name='最小基础技能伤害')),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='heroes.Hero', verbose_name='英雄')),
            ],
        ),
    ]
